Catkin-ProjectName: gentypelibxml
Version: 0.0.0
Description: ros message generation, typelibxml style.
Author: Troy Straszheim <straszheim@willowgarage.com>
Maintainer: Troy Straszheim <straszheim@willowgarage.com>
Homepage: http://www.ros.org

Depends: catkin, genmsg

Catkin-CopyrightType:  willowgarage
Catkin-DebRulesType: python_distutils
Catkin-ROS-Message-Generator: typelibxml

Release-Pull: git://github.com/wg-debs/gentypelibxml.git
Release-Push: git@github.com:wg-debs/gentypelibxml.git

